developers onboarding action added
Classiq/classiq-library pull request #541
Opened 2024-10-17 09:31 UTC by Mayank77maruti

### PR Description

Closes #538 

This PR introduces a new GitHub Action that automatically posts a comment on a pull request once it has been merged into the main branch.

### Some notes

- [x] Please make sure that you placed the files in an appropriate folder
- [x] And that the files have indicative names.

- [x] Please note that Classiq runs automatic code linting, which may minorly alter some files.
- [] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

2024-10-20 09:02 UTC, amir-naveh commented
Great, thanks! @TaliCohn - could you please review the text that is sent? I think we may want something more concise and related to the repo. Let me know if you want to discuss. Once you are good with it you can approve.

2024-10-20 13:18 UTC, TaliCohn requested changes

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                           `For any support, feel free to reach out to the developer onboarding lead: @${mention}. Happy coding! 👩‍💻👨‍💻`;
`${emoji} **Fantastic work @${author}!** Your very first PR to ${repo} has been merged! 🎉🥳\n\n` +
                           `If you're feeling adventurous, why not dive into another issue and keep contributing? The Classiq community would love to see more from you! 🚀\n\n` +
                     Happy coding! 👩‍💻👨‍💻`;

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                           `Looking forward to seeing even more contributions from you. The developer onboarding lead: @${mention} is here if you need any help! Keep up the great work! 🚀`;
Great, please erase the "The developer onboarding lead: @${mention} is here if you need any help!"

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                           `Remember, @${mention} is always here to support you. Keep blazing that trail! 🚀`;
erase: "Remember, @${mention} is always here to support you."

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                           `@${mention} and the whole team applaud your efforts. You're a superstar! 🌟`;
`${emoji} **High five, @${author}!** You've hit the incredible milestone of 5 merged PRs! 🖐️✨\n\n` +
                           `Your dedication to ${repo} is outstanding. You're not just contributing code; you're shaping the future of quantum computing! 🌠\n` +
                           `We'd love to hear your thoughts on the project. Any ideas for new features or improvements? 🤔\n\n` +
                     You're a superstar! 🌟`;

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                           `@${mention} and everyone here are in awe of your contributions. You're an open source hero! 🦸‍♀️🦸‍♂️`;
`${emoji} **Double digits, @${author}!** 10 merged PRs is a massive achievement! 🏆🎊\n\n` +
                           `Your impact on ${repo} is undeniable. You've become a pillar of our community! 🏛️\n` +
                   You're a quantum hero! 🦸‍♀️🦸‍♂️`;

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                             `@${mention} and the entire team are grateful for your dedication. You're an inspiration to us all! 💫`;
`${emoji} **Incredible, @${author}!** You've merged your ${count}th PR! 🎯🎊\n\n` +
                             `Your ongoing commitment to ${repo} is truly remarkable. You're a driving force in our community! 🚀\n` +
                             `Your contributions are helping to shape the future of quantum computing! What exciting features or improvements do you envision next? 🔮\n\n` +
                             `We are grateful for your dedication! 💫`;

2024-10-20 13:18 UTC, TaliCohn commented on .github/workflows/developers_onboarding_notification.yml
> +                             `@${mention} is here if you need any guidance. Onward and upward! 🚀`;
Erase: "`@${mention} is here if you need any guidance. Onward and upward! 🚀`;"

2024-10-25 06:41 UTC, Mayank77maruti commented
Hey @TaliCohn , the pr is ready to be reviewed.
Please do review it.

2024-10-26 18:29 UTC, Mayank77maruti commented
Hey @amir-naveh  , could you please review the pr.
I am participating in a opensource competition and it would be really great if you could review this pr.

2024-10-28 09:37 UTC, TaliCohn approved these changes

2024-10-28 09:37 UTC, merged