feat(github): Add New issue Form
Classiq/classiq-library pull request #560
Opened 2024-10-21 15:06 UTC by utsavdotdev

### PR Description
Introduces the new issue template using YML schema form. 
Fix #519 

### Some notes

- [x] Please make sure that you placed the files in an appropriate folder
- [x] And that the files have indicative names.

- [x] Please note that Classiq runs automatic code linting, which may minorly alter some files.
  - [x] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

2024-10-21 17:20 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +            required: true
This doesn't have to be mandatory. We are happy to get multiple reports about the same bug.

2024-10-21 17:21 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +            required: true
This is unnecessary, can be deleted.

2024-10-21 17:22 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/docs_improvement.yml
> +            required: true
This doesn't have to be mandatory.

2024-10-21 17:25 UTC, TaliCohn requested changes

2024-10-21 17:25 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/docs_improvement.yml
> +            required: true
This is unnecessary, can be deleted.

2024-10-21 17:25 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +          required: true
This doesn't have to be mandatory.

2024-10-21 17:25 UTC, TaliCohn commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +            required: true
This is unnecessary, can be deleted.

2024-10-22 00:40 UTC, utsavdotdev commented
Got it. I will push the required changes.

2024-10-22 00:50 UTC, utsavdotdev commented
@TaliCohn , I have made the required changes. Can you review it?

2024-10-28 09:43 UTC, TaliCohn requested changes
Please delete this from all the forms. As I mentioned, we do not mind having duplicated issues and we don't wont people not to report because of this section. 

 attributes:
   label: "👀 Have you spent some time to check if this feature request has been raised before?"
      options:
        - label: "I checked and didn't find similar issue"
          required: false

2024-10-28 09:45 UTC, utsavdotdev commented
ok

2024-10-28 09:51 UTC, utsavdotdev commented
@TaliCohn , Added the Requested changes

2024-10-30 16:37 UTC, TaliCohn approved these changes

2024-11-04 12:29 UTC, NadavClassiq commented
Hello @utsavdotdev!
Could you please rebase your branch on top of the main branch?

2024-11-04 13:11 UTC, utsavdotdev commented
@NadavClassiq Done

2024-11-05 12:16 UTC, NadavClassiq commented
Hello again, @utsavdotdev !

Thanks for the quick response. It looks like GitHub flagged an issue with this PR, possibly due to a `git merge` instead of a `git rebase` (which is our methodology here in this repo).

To ensure you’re credited as the contributor, could you open a new PR from an updated branch? Please update your fork, then either download the files and start a new branch or cherry-pick the commit from this branch.

Let us know if you need any help!

2024-11-18 09:23 UTC, closed without merging